version: "3.8"
services:
  book-locator-service-pg:
    image: postgres:11-alpine
    container_name: "book-locator-service-pg"
    ports:
      - 5436:5432
    environment:
      - POSTGES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book-locator-service
    restart: always
