kumuluzee:
  dev:
    scan-libraries:
      - book-locator-service-v1-lib

  name: book-locator-service
  version: ${project.version}
  env:
    name: dev
  server:
    base-url: http://localhost:8080
    context-path: /book-locator-service/v1

  datasources:
    - jndi-name: jdbc/BookLocatorDS
      connection-url: jdbc:postgresql://localhost:5436/book-locator-service
      username: postgres
      password: postgres
      pool:
        max-size: 10

  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/BookLocatorDS

  openapi-mp:
    enabled: true
    servlet:
    ui:
      enabled: true

  version-info:
    endpoint: /version

  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET,POST,PUT,PATCH,HEAD,OPTIONS"

  jcache:
    caffeine:
      caffeine.jcache:
        lookup:
          key-type: java.lang.String
          value-type: java.util.Map
