TRUNCATE udks_lookup;

INSERT INTO udks_lookup (id, created_at, created_by, updated_at, updated_by, version, code, name) VALUES
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Igroknjige', 'CMKK-Spodbujevalne, didaktične slikanice'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Slikanice', 'CMKK-Slikanice'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Slikanice-poezija', 'Poezija v slikanici'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Slikanice-uganke', 'Uganke za najmljaše'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Slikanice "+"', 'Zahtevne slikanice'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Zgodbice', 'CMKK-Pripovedi ljudskega ali avtorskega izvora za mlajše, nesamostojne bralce'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Zbirke pravljic', 'CMKK-Zbirke neodvisnih klasičnih ali sodobnih pravljic'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Stripi', 'CMKK-Stripi za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Fantastika', 'CMKK-Fantazijska proza'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Resničnost', 'CMKK-Mladinska proza realnega okolja'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Poezija', 'CMKK-Mladinska poezija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Poezija-uganke', 'Mladinske uganke'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Dramatika', 'CMKK-Mladinska dramatika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '0', 'Znanost. Kultura. Splošno'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '004', 'Računalništvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '005', 'Menedžment'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '01', 'Bibliografije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '02', 'Bibliotekarstvo. Knjižnice. Branje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '03', 'Enciklopedije. Leksikoni. Priročniki'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '05', 'Serijske publikacije. Letopisi. Almanahi. Koledarji'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '06', 'Korporacije. Društva. Muzeji'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '070', 'Novinarstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '1', 'Filozofija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '13 feng šui', 'Feng šui'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '133', 'Okultizem, ezoterika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '159.9', 'Psihologija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '16', 'Logika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '17', 'Etika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '2', 'Verstvo -splošno'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '21/24', 'Primarna verstva. Verstva Daljnega vzhoda. Indijska verstva'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '25', 'Verstva starega sveta'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '26/27', 'Judovstvo. Krščanstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '28', 'Islam'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '29', 'Sodobna duhovna gibanja'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '30', 'Socialna politika. Študije spolov. Sociografija.'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '311+314', 'Statistika. Demografija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '316', 'Sociologija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '316.77', 'Sociologija komunikacij'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '32', 'Politika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '32 slo', 'Politika Slovenije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '33', 'Ekonomija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '331', 'Delo. Zaposlovanje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '336', 'Finance'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '338.48', 'Turizem'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '34', 'Pravo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '343', 'Kazensko pravo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '34(094.5) slo', 'Slovenski zakoni. Predpisi'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '34(094.5) EU', 'Zakoni EU. Predpisi'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '35', 'Javna uprava'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '355/359', 'Vojne vede'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '36', 'Socialno varstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '37', 'Vzgoja in izobraževanje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '373.2/.3', 'Predšolska vzgoja. Osnovna šola'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '373.5+378', 'Srednja šola. Visoko šolstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '374', 'Dodatno izobraževanje. Izobraževanje odraslih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '376', 'Vzgoja in izobraževanje skupin in oseb s posebnimi potrebami'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '39', 'Etnologija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '39 slo', 'Etnologija Slovenije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '391', 'Moda. Oblačilna  kultura. Narodne noše'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '395', 'Bonton'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '398', 'Ljudsko slovstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '398 slo', 'Slovensko ljudsko slovstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '5', 'Naravoslovne vede - splošno'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '502/504', 'Ekologija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '51', 'Matematika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '52', 'Astronomija. Geodezija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '53', 'Fizika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '54', 'Kemija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '55', 'Geologija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '551.5', 'Meteorologija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '56', 'Paleontologija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '57', 'Biologija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '58', 'Rastlinstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '59', 'Živalstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '6/60', 'Uporabne vede. Biotehnologija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '61', 'Medicina'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '613', 'Higiena. Nega. Kozmetika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '613.2', 'Diete. Zdrava prehrana'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '613.81/.84', 'Odvisnosti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '613.88', 'Spolna vzgoja'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '613.95', 'Nega otrok'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '614', 'Javno zdravstvo. Nezgode. Prva pomoč'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '615', 'Farmacija. Zdravila. Zdravilne rastline'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '615.8', 'Alternativna medicina.    Fizioterapija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '615.851', 'Psihoterapija.  Duševno zdravje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '616', 'Patologija. Klinična medicina'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '618', 'Ginekologija. Porodništvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '62', 'Inženirstvo. Tehnologija na splošno.'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '621', 'Strojništvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '621.3', 'Elektrotehnika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '628.5', 'Varstvo pri delu'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '629', 'Tehnika vozil'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '624+69', 'Gradbeno inženirstvo. Gradbeništvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '63', 'Kmetijstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '630', 'Gozdarstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '634.1', 'Sadjarstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '634.8', 'Vinogradništvo. Vinarstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '635', 'Vrtnarstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '635.8', 'Gobarstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '635.9', 'Okrasne rastline'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '636/637', 'Živinoreja. Veterina'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '636.6/.9', 'Hišne živali'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '638.1', 'Čebelarstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '639', 'Lov. Ribolov. Ribogojstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '64', 'Gostinstvo. Gospodinjstvo. Stanovanje. Oblačila'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '641', 'Kuharske knjige'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '654', 'Telekomunikacije in službe obveščanja'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '655', 'Tiskarstvo. Založništvo. Knjigotrštvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '656', 'Pošta. Promet'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '657', 'Računovodstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '659', 'Oglaševanje. Odnosi z javnostmi'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '66/68', 'Industrije in obrti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '7 A-Ž', 'Likovni umetniki'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '7.0', 'Umetnost -teorija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '71', 'Urbanizem. Prostorsko urejanje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '72', 'Arhitektura'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '73', 'Kiparstvo in umetna obrt'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '737', 'Numizmatika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '74', 'Risanje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '745', 'Uporabna umetnost'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '746', 'Ročna dela (tudi  646.2 - pletenje, kvačkanje…)'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '747/749', 'Industrijsko oblikovanje. Domača umetnost in obrt.'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '75', 'Slikarstvo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '76', 'Grafika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '77', 'Fotografija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '78', 'Glasba'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '791', 'Kinematografija. Film'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '792', 'Gledališče'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '792.8', 'Koreografija. Balet. Ples'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '793/794', 'Družabne igre'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '794.1', 'Šah'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '796/799', 'Šport'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '796.3', 'Igre z žogo'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '796.4', 'Gimnastika. Atletika. Telovadba'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '796.5', 'Pohodništvo. Taborjenje. Alpinizem'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'v 796.5', 'Planinski vodniki'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '796.6/.7', 'Kolesarjenje in motošport'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '796.8', 'Borilni in obrambni športi'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '796.9', 'Zimski športi'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '797', 'Vodni športi. Letalski šport'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '798', 'Jahalni športi'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '80/81', 'Jezikoslovje - splošno'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 ang', 'Angleščina - jezikoslovje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 fra', 'Francoščina - jezikoslovje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 ita', 'Italijanščina - jezikoslovje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 gr+lat', 'Latinščina in klasična grščina'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 nem', 'Nemščina - jezikoslovje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 rus', 'Ruščina - jezikoslovje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 slo', 'Slovenščina - jezikoslovje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 slot', 'Slovenščina za tujce'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 shb', 'Srbščina, hrvaščina, bosanščina - jezikoslovje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 špa', 'Španščina - jezikoslovje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '811 ost', 'Jezikoslovje drugih posameznih jezikov'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 's 811', 'slovarji'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '808', 'Retorika. Kreativno pisanje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '82.0', 'Literarna teorija. Kritike'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821.09', 'Literarna zgodovina in literarne študije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821.09 slo', 'Zgodovina in študije slovenske književnosti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821.09 ang', 'Zgodovina  in študije  angleške književnosti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821.09 fra', 'Zgodovina  in študije francoske književnosti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821.09 ita', 'Zgodovina  in študije italijanske književnosti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821.09 gr+lat', 'Zgodovina in študije  latinske in starogrške književnosti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821.09 nem', 'Zgodovina  in študije nemške književnosti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821.09 rus', 'Zgodovina  in študije ruske književnosti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821.09 shb', 'Zgodovina  in študije srbske, hrvaške in bosanske književnosti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821.09 špa', 'Zgodovina  in študije španske književnosti'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.2', 'Družbeni romani'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.2 slo', 'Slovenski družbeni romani'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-32', 'Kratka proza'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-32 slo', 'Slovenska kratka proza'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.4', 'Kriminalni romani in novele'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.4 slo', 'Slovenski kriminalni romani in novele'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.3', 'Pustolovski romani'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.3 slo', 'Slovenski pustolovski romani'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.6', 'Zgodovinski in vojni romani'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.6 slo', 'Slovenski zgodovinski in vojni romani'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-7', 'Satirični romani. Humor. Anekdote'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-7 slo', 'Slovenski satirični romani. Humor. Anekdote'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.9', 'Znanstvena fantastika. Fantastični romani in novele'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.9 slo', 'Slovenska znanstvena fantastika. Fantastični romani in novele'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.6', 'Biografski romani'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.6 slo', 'Slovenski biografski romani'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-1', 'Poezija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-1 slo', 'Slovenska poezija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-2', 'Dramatika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-2 slo', 'Slovenska dramatika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821 A-Ž', 'Zbrana in izbrana dela'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821 A-Ž slo', 'Slovenska zbrana in izbrana dela'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-4', 'Eseji'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-4 slo', 'Slovenski eseji'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-5/-6', 'Govori, pisma'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-5/-6 slo', 'Slovenski govori, pisma'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-82', 'Antologije. Poligrafije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-82 slo', 'Slovenske antologije. Poligrafije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-84', 'Aforizmi. Misli. Pregovori'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-84 slo', 'Slovenski aforizmi. Misli. Pregovori'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-94', 'Spomini. Dnevniki. Reportaže'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-94 slo', 'Slovenski spomini. Dnevniki. Reportaže'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-992', 'Potopisi'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-992 slo', 'Slovenski potopisi'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.2=ang', 'Družbeni romani v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-32=ang', 'Kratka proza  v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.4=ang', 'Kriminalni romani in novele v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.3=ang', 'Pustolovski romani v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.6=ang', 'Zgodovinski in vojni romani v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-7=ang', 'Satirični romani. Humor. Anekdote v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.9=ang', 'Znanstvena fantastika. Fantastični romani in novele v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.6=ang', 'Biografski romani v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-1=ang', 'Poezija v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-2=ang', 'Dramatika v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821 A-Ž=ang', 'Zbrana in izbrana dela v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-4=ang', 'Eseji v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-5/-6=ang', 'Govori, pisma v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-82=ang', 'Antologije. Poligrafije v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-84=ang', 'Aforizmi. Misli. Pregovori v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-94=ang', 'Spomini. Dnevniki. Reportaže v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-992=ang', 'Potopisi v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.2=fra', 'Družbeni romani v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-32=fra', 'Kratka proza  v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.4=fra', 'Kriminalni romani in novele v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.3=fra', 'Pustolovski romani v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.6=fra', 'Zgodovinski in vojni romani v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-7=fra', 'Satirični romani. Humor. Anekdote v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.9=fra', 'Znanstvena fantastika. Fantastični romani in novele v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.6=fra', 'Biografski romani v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-1=fra', 'Poezija v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-2=fra', 'Dramatika v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821 A-Ž=fra', 'Zbrana in izbrana dela v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-4=fra', 'Eseji v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-5/-6=fra', 'Govori, pisma v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-82=fra', 'Antologije. Poligrafije v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-84=fra', 'Aforizmi. Misli. Pregovori v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-94=fra', 'Spomini. Dnevniki. Reportaže v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-992=fra', 'Potopisi v francoščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.2=nem', 'Družbeni romaniv nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-32=nem', 'Kratka proza v nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.4=nem', 'Kriminalni romani in novelev nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.3=nem', 'Pustolovski romaniv nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.6=nem', 'Zgodovinski in vojni romaniv nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-7=nem', 'Satirični romani. Humor. Anekdotev nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.9=nem', 'Znanstvena fantastika. Fantastični romani in novelev nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.6=nem', 'Biografski romaniv nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-1=nem', 'Poezijav nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-2=nem', 'Dramatikav nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821 A-Ž=nem', 'Zbrana in izbrana delav nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-4=nem', 'Esejiv nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-5/-6=nem', 'Govori, pismav nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-82=nem', 'Antologije. Poligrafijev nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-84=nem', 'Aforizmi. Misli. Pregovoriv nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-94=nem', 'Spomini. Dnevniki. Reportažev nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-992=nem', 'Potopisiv nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.2=špa', 'Družbeni romaniv španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-32=špa', 'Kratka proza v španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.4=špa', 'Kriminalni romani in novelev španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.3=špa', 'Pustolovski romaniv španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.6=špa', 'Zgodovinski in vojni romaniv španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-7=špa', 'Satirični romani. Humor. Anekdotev španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.9=špa', 'Znanstvena fantastika. Fantastični romani in novelev španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.6=špa', 'Biografski romaniv španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-1=špa', 'Poezijav španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-2=špa', 'Dramatikav španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821 A-Ž=špa', 'Zbrana in izbrana delav španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-4=špa', 'Esejiv španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-5/-6=špa', 'Govori, pismav španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-82=špa', 'Antologije. Poligrafijev španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-84=špa', 'Aforizmi. Misli. Pregovoriv španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-94=špa', 'Spomini. Dnevniki. Reportažev španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-992=špa', 'Potopisiv španščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.2=ita', 'Družbeni romani v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-32=ita', 'Kratka proza  v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.4=ita', 'Kriminalni romani in novele v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.3=ita', 'Pustolovski romani v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.6=ita', 'Zgodovinski in vojni romani v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-7=ita', 'Satirični romani. Humor. Anekdote v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.9=ita', 'Znanstvena fantastika. Fantastični romani in novele v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.6=ita', 'Biografski romani v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-1=ita', 'Poezija v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-2=ita', 'Dramatika v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821 A-Ž=ita', 'Zbrana in izbrana dela v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-4=ita', 'Eseji v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-5/-6=ita', 'Govori, pisma v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-82=ita', 'Antologije. Poligrafije v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-84=ita', 'Aforizmi. Misli. Pregovori v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-94=ita', 'Spomini. Dnevniki. Reportaže v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-992=ita', 'Potopisi v italijanščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.2=shb', 'Družbeni romani v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-32=shb', 'Kratka proza  v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.4=shb', 'Kriminalni romani in novele v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.3=shb', 'Pustolovski romani v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.6=shb', 'Zgodovinski in vojni romani v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-7=shb', 'Satirični romani. Humor. Anekdote v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.9=shb', 'Znanstvena fantastika. Fantastični romani in novele v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.6=shb', 'Biografski romani v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-1=shb', 'Poezija v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-2=shb', 'Dramatika v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821 A-Ž=shb', 'Zbrana in izbrana dela v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-4=shb', 'Eseji v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-5/-6=shb', 'Govori, pisma v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-82=shb', 'Antologije. Poligrafije v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-84=shb', 'Aforizmi. Misli. Pregovori v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-94=shb', 'Spomini. Dnevniki. Reportaže v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-992=shb', 'Potopisi v južnoslovanskih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.2=rus', 'Družbeni romani v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-32=rus', 'Kratka proza  v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.4=rus', 'Kriminalni romani in novele v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.3=rus', 'Pustolovski romani v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.6=rus', 'Zgodovinski in vojni romani v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-7=rus', 'Satirični romani. Humor. Anekdote v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.9=rus', 'Znanstvena fantastika. Fantastični romani in novele v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.6=rus', 'Biografski romani v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-1=rus', 'Poezija v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-2=rus', 'Dramatika v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821 A-Ž=rus', 'Zbrana in izbrana dela v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-4=rus', 'Eseji v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-5/-6=rus', 'Govori, pisma v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-82=rus', 'Antologije. Poligrafije v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-84=rus', 'Aforizmi. Misli. Pregovori v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-94=rus', 'Spomini. Dnevniki. Reportaže v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-992=rus', 'Potopisi v ruščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.2=ost', 'Družbeni romani v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-32=ost', 'Kratka proza  v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.4=ost', 'Kriminalni romani in novele v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.3=ost', 'Pustolovski romani v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-311.6=ost', 'Zgodovinski in vojni romani v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-7=ost', 'Satirični romani. Humor. Anekdote v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.9=ost', 'Znanstvena fantastika. Fantastični romani in novele v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-312.6=ost', 'Biografski romani v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-1=ost', 'Poezija v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-2=ost', 'Dramatika v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821 A-Ž=ost', 'Zbrana in izbrana dela v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-4=ost', 'Eseji v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-5/-6=ost', 'Govori, pisma v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-82=ost', 'Antologije. Poligrafije v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-84=ost', 'Aforizmi. Misli. Pregovori v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-94=ost', 'Spomini. Dnevniki. Reportaže v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '821-992=ost', 'Potopisi v ostalih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) ang 1', 'Poenostavljene angleške izdaje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) ang 2', 'Poenostavljene angleške izdaje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) ang 3', 'Poenostavljene angleške izdaje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) ang 4', 'Poenostavljene angleške izdaje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) ang 5', 'Poenostavljene angleške izdaje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) ang 6', 'Poenostavljene angleške izdaje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) ang 7', 'Poenostavljene angleške izdaje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) nem', 'Poenostavljene nemške izdaje'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) fra', 'Poenostavljene francoske izdaje (brez stopenj)'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) ita', 'Poenostavljene italijanske izdaje (brez stopenj)'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) slo', 'Poenostavljene izdaje v slovenščini (brez stopenj)'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) špa', 'Poenostavljene španske izdaje (brez stopenj)'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) rus', 'Poenostavljene ruske izdaje (brez stopenj)'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '8(0.046) ost', 'Poenostavljene izdaje drugih jezikov (brez stopenj)'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '91', 'Zemljepis splošno'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '91(4)', 'Evropa'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '91 slo', 'Slovenija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '91(5)', 'Azija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '91(6)', 'Afrika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '91(7/8)', 'Amerika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '91(9)', 'Avstralija. Oceanija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '91 Ljubljana', 'Geografija in domozanstvo Ljubljane'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'v 9(100)', 'Turistični vodniki , zemljevidi'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'v 9(4)', 'Turistični vodniki po Evropi'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'v 9 slo', 'Turistični vodniki po Sloveniji'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'v 9(5)', 'Turistični vodniki po Aziji'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'v 9(6)', 'Turistični vodniki po Afriki'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'v 9(7/8)', 'Turistični vodniki po Ameriki'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'v 9(9)', 'Turistični vodniki po Avstraliji, Oceaniji, Antarktiki'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '902/904', 'Arheologija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '929 A-Ž', 'Biografije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '929.5/.9', 'Rodoslovje. Heraldika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '930', 'Zgodovinska znanost. Arhivistika.'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '930.85 slo', 'Kulturna zgodovina Slovenije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '930.85', 'Kulturna zgodovina'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94', 'Svetovna zgodovina'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94".../04"', 'Zgodovina starega veka'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94"1914/1918"', 'Prva svetovna vojna'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94"1939/1945"', 'Druga svetovna vojna'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94"41/45" slo', 'Druga svetovna vojna - Slovenija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94(4)', 'Zgodovina Evrope'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94 slo', 'Zgodovina Slovenije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94 Ljubljana', 'Zgodovina Ljubljane'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94(5)', 'Zgodovina Azije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94(6)', 'Zgodovina Afrike'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94(7/8)', 'Zgodovina Amerike'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '94(9)', 'Zgodovina Avstralije in Oceanije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'ml filmi', 'Filmi za otroke in mladimno'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'ml glasba', 'Glasba za otroke in mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'ml poezija', 'Mladinska poezija na NBM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'ml pripovedi', 'Mladinsko leposlovje na NBM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'ml pripovedi=ang', 'Mladisnko leposlovje na NBM v angleščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'ml pripovedi=nem', 'Mladisnko leposlovje na NBM v nemščini'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'ml pripovedi=ost', 'Mladisnko leposlovje na NBM v drugih tujih jezikih'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'ml risanke', 'Risane serije za otroke in mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Igrače 1+', 'igrače za otroke od rojstva naprej'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Igrače 2+', 'igrače za otroke od drugega leta naprej'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Igrače 3+', 'igrače za otroke od tretjega leta naprej'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Igrače 4+', 'igrače za otroke od četrtega leta naprej'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Igrače 5+', 'igrače za otroke od petega leta naprej'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Igrače 6+', 'igrače za otroke od šestega leta naprej (izobraževalne igrače)'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Igrače 8+', 'igrače za otroke od osmega leta naprej (izobraževalne igrače)'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Igrače 10+', 'igrače za otroke od desetega leta naprej (družabne igre-za mladostnike in odrasle)'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 0', 'Splošno o vedah in znanjih - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 03', 'Enciklopedije - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 004', 'Računalništvo - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 1', 'Filozofija  - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 17', 'Etika - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 159', 'Psihologija  - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 2', 'Verstva in mitologije - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 27', 'Krščanstvo - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 3', 'Družboslovje - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 37', 'Vzgoja - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 39', 'Etnologija  - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 395', 'Bonton  - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 5', 'Naravoslovje - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 502', 'Ekologija - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 51', 'Matematika - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 52', 'Astronomija  - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 53', 'Fizika - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 54', 'Kemija - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 55', 'Geologija, vremenoslovje - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 56', 'Paleontologija (dinozavri, fosili) - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 57', 'Biologija - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 58', 'Rastlinstvo - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 59', 'Živalstvo - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 61', 'Medicina - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 613.8', 'Odvisnosti - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 613.88', 'Spolna vzgoja - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 62', 'Tehnika - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 63', 'Gojenje rastlin, vzreja živali  - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 64', 'Gospodinjstvo  - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 65', 'Promet, trgovina - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 67', 'Industrija, obrti - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 7', 'Umetnost - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 745', 'Ročne spretnosti - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 78', 'Glasba - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 794', 'Družabne igre - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 796', 'Šport - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 8', 'Jezikoslovje, književnost - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M s81', 'Mladinski slovarji'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 81 slo', 'Slovenščina  - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 81 ang', 'Angleščina za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 81 ost', 'Tuji jeziki - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 91', 'Zemljepis  - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 91 slo', 'Zemljepis Slovenije - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 929', 'Življenjepisi - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 94', 'Zgodovina - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M 94 slo', 'Zgodovina Slovenije - za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'C=ang', 'Leposlovje v angleščini za najmlajše'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M=ang', 'Leposlovje v angleščini za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'C=nem', 'Leposlovje v nemščini za najmlajše'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M=nem', 'Leposlovje v nemščini za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'C=fra', 'Leposlovje v francoščini za najmlajše'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M=fra', 'Leposlovje v francoščini za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'C=špa', 'Leposlovje v španščini za najmlajše'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M=špa', 'Leposlovje v španščini za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'C=ita', 'Leposlovje v italijanščini za najmlajše'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M=ita', 'Leposlovje v italijanščini za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'C=shb', 'Leposlovje v srbšč., hrvaš., bosan. za najmlajše'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M=shb', 'Leposlovje v srbšč., hrvaš., bosan. za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'C=rus', 'Leposlovje v ruščini za najmlajše'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M=rus', 'Leposlovje v ruščini za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'C=ost', 'Leposlovje v raznih tujih jezikih za najmlajše'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'M=ost', 'Leposlovje v raznih tujih jezikih za mladino'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'blues', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'božična', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'elektronska', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'filmska', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'jazz', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'klasična', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'ljudska', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'narodnozabavna', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'meditativna', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'plesna', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'popularna', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'šanson', 'GLASBA'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'akcijski', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'animirani', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'biografski', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'burleska', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'dokumentarni', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'drama', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'fantazijski', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'glasbeni', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'grozljivka', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'komedija', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'kriminalka', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'melodrama', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'pustolovski', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'srhljivka', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'vestern', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'vojni', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'zgodovinski', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'znan-fant.', 'FILM'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'spletni dostop', 'Podatkovne zbirke'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'BRALNIK', 'Gradivo na bralniku'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'KOVČEK', 'Moja prva knjižnica - kovček'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'n J', 'note'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'n K', 'note'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'n V', 'note'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'n Z', 'note'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Stripi=ost', 'Tujejezični stripi za otroke'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'Hiša svetov', 'Zbirka HUMANITAS'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, 'ZZB-NOB', 'Zbirka NOB pri ZB'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '084.11 teo', 'Stripi - teorija'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '084.11 rz', 'Stripi - risane zgodbe'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '084.11 slo', 'Stripi - slovenika'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '084.11 ant', 'Stripi - antologije'),
(gen_random_uuid(), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 1, '084.11 hum', 'Stripi - humor');